import type { Lesson, WidgetConfig } from "@/lib/lesson-types";

export const positionDirectionLesson: Lesson = {
  id: "grade3-sem2-position-direction",
  entry: 1,
  chapter: 1,
  title: "位置与方向（一）",
  subtitle: "三年级下册 · 位置与方向",
  backHref: "/",
  backLabel: "返回目录",
  footerNote: "参考：人教版三年级下册 · 第 1 章 p.2–10",
  nextLesson: {
    href: "/lesson/division",
    title: "除数是一位数的除法",
  },
  objectives: [
    "认识东、南、西、北四个基本方向",
    "能在地图上辨认方向（上北下南、左西右东）",
    "能描述物体所在的方向",
    "初步认识东北、东南、西北、西南四个方向",
    "能根据方向描述简单路线",
  ],
  intro:
    "出门看太阳、看地图找路，都离不开方向。这一章我们一起来认识东、南、西、北，还有东北、东南、西北、西南，学会用方向描述身边物体的位置。",
  steps: [
    {
      id: "step-1",
      title: "认识东、南、西、北",
      caption: "图 1 · 早晨的太阳",
      narration:
        "早晨，太阳从东方升起。小明面向东，背对着的方向是西，左边是北，右边是南。东与西相对，北与南相对。",
      widget: {
        kind: "position-map",
        props: {
          mode: "identify",
          rows: 3,
          cols: 3,
          places: [
            { id: "小明", label: "小明", row: 1, col: 1 },
            { id: "太阳", label: "太阳", row: 1, col: 2, color: "#f59e0b" },
          ],
          reference: "小明",
          target: "太阳",
          answer: "east",
          options: ["east", "south", "west", "north"],
          prompt: "太阳在小明的什么方向？",
        },
      } as unknown as WidgetConfig,
    },
    {
      id: "step-2",
      title: "地图上的方向",
      caption: "图 2 · 上北下南，左西右东",
      narration:
        "地图通常是按上北下南、左西右东绘制的。看这幅校园示意图，操场在中间，大门在操场的下面，也就是在操场的南面。",
      widget: {
        kind: "position-map",
        props: {
          mode: "identify",
          rows: 3,
          cols: 3,
          places: [
            { id: "教学楼", label: "教学楼", row: 0, col: 1 },
            { id: "体育馆", label: "体育馆", row: 1, col: 0 },
            { id: "操场", label: "操场", row: 1, col: 1 },
            { id: "图书馆", label: "图书馆", row: 1, col: 2 },
            { id: "大门", label: "大门", row: 2, col: 1 },
          ],
          reference: "操场",
          target: "大门",
          answer: "south",
          options: ["east", "south", "west", "north"],
          prompt: "大门在操场的什么方向？",
        },
      } as unknown as WidgetConfig,
    },
    {
      id: "step-3",
      title: "校园方位练一练",
      caption: "图 3 · 校园里的相对位置",
      narration:
        "知道了方向标，就能说出任意两个地点的相对位置。例如：教学楼在操场的北面，体育馆在操场的西面。",
      widget: {
        kind: "position-map",
        props: {
          mode: "identify",
          rows: 3,
          cols: 3,
          places: [
            { id: "教学楼", label: "教学楼", row: 0, col: 1 },
            { id: "体育馆", label: "体育馆", row: 1, col: 0 },
            { id: "操场", label: "操场", row: 1, col: 1 },
            { id: "图书馆", label: "图书馆", row: 1, col: 2 },
            { id: "大门", label: "大门", row: 2, col: 1 },
          ],
          reference: "体育馆",
          target: "图书馆",
          answer: "east",
          options: ["east", "south", "west", "north"],
          prompt: "图书馆在体育馆的什么方向？",
        },
      } as unknown as WidgetConfig,
    },
    {
      id: "step-4",
      title: "认识东北、东南、西北、西南",
      caption: "图 4 · 八个方向",
      narration:
        "除了东、南、西、北，还有四个斜向方向：东北、东南、西北、西南。多功能厅在校园的东北角。",
      widget: {
        kind: "position-map",
        props: {
          mode: "identify",
          rows: 3,
          cols: 3,
          places: [
            { id: "食堂", label: "食堂", row: 0, col: 0 },
            { id: "教学楼", label: "教学楼", row: 0, col: 1 },
            { id: "多功能厅", label: "多功能厅", row: 0, col: 2 },
            { id: "体育馆", label: "体育馆", row: 1, col: 0 },
            { id: "操场", label: "操场", row: 1, col: 1 },
            { id: "图书馆", label: "图书馆", row: 1, col: 2 },
            { id: "存车处", label: "存车处", row: 2, col: 0 },
            { id: "科技楼", label: "科技楼", row: 2, col: 1 },
            { id: "大门", label: "大门", row: 2, col: 2 },
          ],
          reference: "存车处",
          target: "食堂",
          answer: "north",
          options: [
            "north",
            "south",
            "west",
            "east",
            "northeast",
            "northwest",
            "southeast",
            "southwest",
          ],
          prompt: "食堂在存车处的什么方向？",
        },
      } as unknown as WidgetConfig,
    },
    {
      id: "step-5",
      title: "动物园导游图",
      caption: "图 5 · 规划参观路线",
      narration:
        "看动物园导游图，小玲想从大门出发去看长颈鹿馆。可以先向北走到狮虎山，再向西北走就能到达长颈鹿馆。",
      widget: {
        kind: "position-map",
        props: {
          mode: "route",
          rows: 4,
          cols: 4,
          places: [
            { id: "猩猩馆", label: "猩猩馆", row: 0, col: 1 },
            { id: "长颈鹿馆", label: "长颈鹿馆", row: 0, col: 2 },
            { id: "飞禽馆", label: "飞禽馆", row: 0, col: 3 },
            { id: "象馆", label: "象馆", row: 1, col: 1 },
            { id: "猴山", label: "猴山", row: 1, col: 2 },
            { id: "狮虎山", label: "狮虎山", row: 2, col: 1 },
            { id: "大门", label: "大门", row: 3, col: 1 },
            { id: "海洋馆", label: "海洋馆", row: 3, col: 0 },
            { id: "大熊猫馆", label: "大熊猫馆", row: 3, col: 2 },
          ],
          route: [
            { from: "大门", to: "狮虎山", direction: "north" },
            { from: "狮虎山", to: "长颈鹿馆", direction: "northwest" },
          ],
          missingLeg: 1,
          options: [
            "north",
            "south",
            "west",
            "east",
            "northeast",
            "northwest",
            "southeast",
            "southwest",
          ],
          prompt: "从大门到长颈鹿馆，第二段路应该向什么方向走？",
        },
      } as unknown as WidgetConfig,
    },
    {
      id: "step-6",
      title: "自由探索",
      caption: "图 6 · 换个观察点",
      narration:
        "换一个观察点，方向描述就会改变。请选择两个地点，看看目标在观察点的什么方向。",
      widget: {
        kind: "position-map",
        props: {
          mode: "explore",
          rows: 4,
          cols: 4,
          places: [
            { id: "猩猩馆", label: "猩猩馆", row: 0, col: 1 },
            { id: "长颈鹿馆", label: "长颈鹿馆", row: 0, col: 2 },
            { id: "飞禽馆", label: "飞禽馆", row: 0, col: 3 },
            { id: "象馆", label: "象馆", row: 1, col: 1 },
            { id: "猴山", label: "猴山", row: 1, col: 2 },
            { id: "狮虎山", label: "狮虎山", row: 2, col: 1 },
            { id: "大门", label: "大门", row: 3, col: 1 },
            { id: "海洋馆", label: "海洋馆", row: 3, col: 0 },
            { id: "大熊猫馆", label: "大熊猫馆", row: 3, col: 2 },
          ],
        },
      } as unknown as WidgetConfig,
    },
  ],
  exercises: [
    {
      id: "zoo-direction",
      title: "动物园导游图",
      description: "大熊猫馆在长颈鹿馆的什么方向？",
      widget: {
        kind: "position-map",
        props: {
          mode: "identify",
          rows: 4,
          cols: 4,
          places: [
            { id: "猩猩馆", label: "猩猩馆", row: 0, col: 1 },
            { id: "长颈鹿馆", label: "长颈鹿馆", row: 0, col: 2 },
            { id: "飞禽馆", label: "飞禽馆", row: 0, col: 3 },
            { id: "象馆", label: "象馆", row: 1, col: 1 },
            { id: "猴山", label: "猴山", row: 1, col: 2 },
            { id: "狮虎山", label: "狮虎山", row: 2, col: 1 },
            { id: "大门", label: "大门", row: 3, col: 1 },
            { id: "海洋馆", label: "海洋馆", row: 3, col: 0 },
            { id: "大熊猫馆", label: "大熊猫馆", row: 3, col: 2 },
          ],
          reference: "长颈鹿馆",
          target: "大熊猫馆",
          answer: "south",
          options: ["east", "south", "west", "north"],
          prompt: "大熊猫馆在长颈鹿馆的什么方向？",
        },
      } as unknown as WidgetConfig,
    },
  ],
  quiz: [
    {
      id: "q1",
      prompt: "早晨，太阳从（  ）方升起。",
      hint: "太阳升起的方向",
      answer: 1,
      choices: [
        { label: "东", value: 1 },
        { label: "南", value: 2 },
        { label: "西", value: 3 },
        { label: "北", value: 4 },
      ],
    },
    {
      id: "q2",
      prompt: "地图通常是按（  ）绘制的。",
      hint: "上北下南，左西右东",
      answer: 1,
      choices: [
        { label: "上北下南，左西右东", value: 1 },
        { label: "上南下北，左西右东", value: 2 },
        { label: "上北下南，左东右西", value: 3 },
        { label: "上东下西，左南右北", value: 4 },
      ],
    },
    {
      id: "q3",
      prompt: "图书馆在操场的东面，那么操场在图书馆的（  ）面。",
      hint: "方向是相对的",
      answer: 3,
      choices: [
        { label: "东", value: 1 },
        { label: "南", value: 2 },
        { label: "西", value: 3 },
        { label: "北", value: 4 },
      ],
    },
    {
      id: "q4",
      prompt: "多功能厅在校园的东北角，科技楼在校园的东南角。科技楼在多功能厅的（  ）方向。",
      hint: "从东北角往左下角看",
      answer: 8,
      choices: [
        { label: "东北", value: 5 },
        { label: "西北", value: 6 },
        { label: "东南", value: 7 },
        { label: "西南", value: 8 },
      ],
    },
    {
      id: "q5",
      prompt: "从动物园大门去长颈鹿馆，可以先向北走到狮虎山，再向（  ）走。",
      hint: "长颈鹿馆在狮虎山的斜上方",
      answer: 6,
      choices: [
        { label: "东北", value: 5 },
        { label: "西北", value: 6 },
        { label: "东南", value: 7 },
        { label: "西南", value: 8 },
      ],
    },
  ],
};
